import { TestPrepItem } from './types'

export const TESTS: TestPrepItem[] = [
  {
    id: 'sat',
    name: 'SAT',
    shortDescription: 'College admission test covering reading, writing, and math',
    whatItIs: 'The SAT is a standardized test widely used for college admissions in the United States. It measures literacy, numeracy, and writing skills needed for academic success in college. The test is administered by the College Board and takes about 3 hours.',
    whoShouldTake: 'High school juniors and seniors planning to attend a four-year college or university. Many colleges accept either SAT or ACT scores, so check your target schools\' requirements.',
    whyItMatters: 'SAT scores are used by colleges to evaluate applicants alongside GPA, extracurriculars, and essays. Strong scores can also qualify you for merit-based scholarships and honors programs.',
    whenToTake: 'Most students take the SAT in spring of junior year or fall of senior year. This allows time to retake if needed. Registration typically opens 2-3 months before each test date.',
    icon: 'school-outline',
    color: '#1976D2',
    bgColor: '#E3F2FD',
    links: [
      { label: 'Official SAT Website', url: 'https://collegereadiness.collegeboard.org/sat' },
      { label: 'Free Practice on Khan Academy', url: 'https://www.khanacademy.org/sat' },
    ],
    milestones: [
      {
        id: 'sat-register',
        label: 'Add registration reminder',
        taskTitle: 'Register for the SAT',
        offsetDays: 30,
        notes: 'Source: Test Prep - SAT',
      },
      {
        id: 'sat-study-plan',
        label: 'Create study plan',
        taskTitle: 'Create SAT study plan',
        offsetDays: 7,
        notes: 'Source: Test Prep - SAT. Aim for 2-3 months of consistent practice.',
      },
      {
        id: 'sat-practice-test',
        label: 'Take practice test',
        taskTitle: 'Complete a full SAT practice test',
        offsetDays: 14,
        notes: 'Source: Test Prep - SAT. Use official College Board practice tests.',
      },
      {
        id: 'sat-accommodations',
        label: 'Ask about accommodations',
        taskTitle: 'Ask counselor about SAT accommodations',
        offsetDays: 60,
        notes: 'Source: Test Prep - SAT. If you have a documented disability, you may qualify for extra time or other accommodations.',
      },
    ],
  },
  {
    id: 'act',
    name: 'ACT',
    shortDescription: 'College readiness test with English, math, reading, and science',
    whatItIs: 'The ACT is a standardized test used for college admissions. It covers English, mathematics, reading, and science reasoning, with an optional writing section. The test takes about 3 hours (plus 40 minutes for writing).',
    whoShouldTake: 'High school juniors and seniors applying to colleges. The ACT is accepted by all four-year colleges in the US. Some students prefer it over the SAT because it includes a science section and has a different format.',
    whyItMatters: 'Like the SAT, ACT scores help colleges evaluate applicants. The ACT also offers a "superscore" option at many schools, where they consider your best section scores across multiple test dates.',
    whenToTake: 'Most students take the ACT in spring of junior year or fall of senior year. The test is offered 7 times per year nationally. Register 4-6 weeks before your preferred test date.',
    icon: 'document-text-outline',
    color: '#388E3C',
    bgColor: '#E8F5E9',
    links: [
      { label: 'Official ACT Website', url: 'https://www.act.org/' },
      { label: 'ACT Academy (Free Prep)', url: 'https://academy.act.org/' },
    ],
    milestones: [
      {
        id: 'act-register',
        label: 'Add registration reminder',
        taskTitle: 'Register for the ACT',
        offsetDays: 30,
        notes: 'Source: Test Prep - ACT',
      },
      {
        id: 'act-study-plan',
        label: 'Create study plan',
        taskTitle: 'Create ACT study plan',
        offsetDays: 7,
        notes: 'Source: Test Prep - ACT. Focus on your weakest sections first.',
      },
      {
        id: 'act-practice-test',
        label: 'Take practice test',
        taskTitle: 'Complete a full ACT practice test',
        offsetDays: 14,
        notes: 'Source: Test Prep - ACT. Time yourself to simulate real test conditions.',
      },
      {
        id: 'act-science-review',
        label: 'Review science section',
        taskTitle: 'Review ACT science section strategies',
        offsetDays: 21,
        notes: 'Source: Test Prep - ACT. The science section tests data interpretation, not science knowledge.',
      },
    ],
  },
  {
    id: 'psat',
    name: 'PSAT/NMSQT',
    shortDescription: 'Preliminary SAT and National Merit Scholarship Qualifying Test',
    whatItIs: 'The PSAT/NMSQT is a practice version of the SAT that also serves as the qualifying test for the National Merit Scholarship Program. It\'s shorter than the SAT (about 2 hours 45 minutes) and covers reading, writing, and math.',
    whoShouldTake: 'High school sophomores and juniors. Juniors who score in the top 1% may qualify as National Merit Semifinalists, which can lead to significant scholarship opportunities.',
    whyItMatters: 'Beyond scholarship opportunities, the PSAT helps you identify strengths and weaknesses before taking the SAT. Your score report includes personalized practice recommendations.',
    whenToTake: 'The PSAT is offered once per year in October. Most schools administer it during the school day. Talk to your counselor about signing up.',
    icon: 'ribbon-outline',
    color: '#7B1FA2',
    bgColor: '#F3E5F5',
    links: [
      { label: 'PSAT/NMSQT Info', url: 'https://collegereadiness.collegeboard.org/psat-nmsqt-psat-10' },
      { label: 'National Merit Scholarship', url: 'https://www.nationalmerit.org/' },
    ],
    milestones: [
      {
        id: 'psat-signup',
        label: 'Sign up at school',
        taskTitle: 'Ask counselor about PSAT registration',
        offsetDays: 14,
        notes: 'Source: Test Prep - PSAT/NMSQT. The PSAT is usually administered at your school in October.',
      },
      {
        id: 'psat-practice',
        label: 'Take practice test',
        taskTitle: 'Complete a PSAT practice test',
        offsetDays: 21,
        notes: 'Source: Test Prep - PSAT/NMSQT. Use official College Board practice materials.',
      },
      {
        id: 'psat-review-scores',
        label: 'Review score report',
        taskTitle: 'Review PSAT score report and recommendations',
        offsetDays: 90,
        notes: 'Source: Test Prep - PSAT/NMSQT. Scores are typically available in December.',
      },
    ],
  },
  {
    id: 'ap',
    name: 'AP Exams',
    shortDescription: 'College-level exams that can earn you college credit',
    whatItIs: 'Advanced Placement (AP) Exams are standardized tests that measure your mastery of college-level material in specific subjects. Scoring well (typically 3-5 on a 5-point scale) can earn you college credit or advanced placement.',
    whoShouldTake: 'Students enrolled in AP courses at their high school. You can also self-study for AP exams if your school doesn\'t offer a particular course. Check your target colleges\' AP credit policies.',
    whyItMatters: 'AP credits can save you time and money in college by allowing you to skip introductory courses. Strong AP scores also demonstrate academic rigor to college admissions officers.',
    whenToTake: 'AP Exams are administered in May each year, typically during the first two weeks. Registration is usually in the fall through your school\'s AP coordinator.',
    icon: 'trophy-outline',
    color: '#F57C00',
    bgColor: '#FFF3E0',
    links: [
      { label: 'AP Central', url: 'https://apcentral.collegeboard.org/' },
      { label: 'AP Exam Schedule', url: 'https://apcentral.collegeboard.org/exam-administration-ordering-scores/exam-dates' },
    ],
    milestones: [
      {
        id: 'ap-register',
        label: 'Register for exams',
        taskTitle: 'Register for AP Exams through school',
        offsetDays: 30,
        notes: 'Source: Test Prep - AP Exams. Registration is typically in the fall.',
      },
      {
        id: 'ap-study-schedule',
        label: 'Create study schedule',
        taskTitle: 'Create AP Exam study schedule',
        offsetDays: 14,
        notes: 'Source: Test Prep - AP Exams. Plan to review all units before the May exam.',
      },
      {
        id: 'ap-practice-frq',
        label: 'Practice free response',
        taskTitle: 'Practice AP free response questions',
        offsetDays: 21,
        notes: 'Source: Test Prep - AP Exams. Free response questions are often worth 50% or more of your score.',
      },
      {
        id: 'ap-check-credit',
        label: 'Check college credit policies',
        taskTitle: 'Research AP credit policies at target colleges',
        offsetDays: 7,
        notes: 'Source: Test Prep - AP Exams. Different colleges have different score requirements for credit.',
      },
    ],
  },
  {
    id: 'asvab',
    name: 'ASVAB',
    shortDescription: 'Armed Services Vocational Aptitude Battery for military careers',
    whatItIs: 'The ASVAB is a multiple-aptitude test that measures developed abilities and helps predict future academic and occupational success in the military. It covers areas like arithmetic, word knowledge, mechanical comprehension, and electronics.',
    whoShouldTake: 'Students interested in joining any branch of the U.S. military (Army, Navy, Air Force, Marines, Coast Guard, Space Force). Your scores determine which military jobs (MOS) you qualify for.',
    whyItMatters: 'Higher ASVAB scores open up more career options in the military, including technical and specialized roles. Some positions require minimum scores in specific areas.',
    whenToTake: 'The ASVAB can be taken at your high school (if offered) or at a Military Entrance Processing Station (MEPS). There\'s no specific season - you can take it when you\'re ready to explore military options.',
    icon: 'shield-outline',
    color: '#455A64',
    bgColor: '#ECEFF1',
    links: [
      { label: 'Official ASVAB Website', url: 'https://www.officialasvab.com/' },
      { label: 'ASVAB Practice Tests', url: 'https://www.4tests.com/asvab' },
    ],
    milestones: [
      {
        id: 'asvab-talk-recruiter',
        label: 'Talk to a recruiter',
        taskTitle: 'Schedule meeting with military recruiter',
        offsetDays: 14,
        notes: 'Source: Test Prep - ASVAB. A recruiter can explain your options and help you prepare.',
      },
      {
        id: 'asvab-practice',
        label: 'Take practice test',
        taskTitle: 'Complete ASVAB practice test',
        offsetDays: 21,
        notes: 'Source: Test Prep - ASVAB. Identify which sections need the most work.',
      },
      {
        id: 'asvab-study-weak',
        label: 'Study weak areas',
        taskTitle: 'Study weak areas for ASVAB',
        offsetDays: 30,
        notes: 'Source: Test Prep - ASVAB. Focus on math and technical sections if pursuing technical roles.',
      },
    ],
  },
  {
    id: 'accuplacer',
    name: 'Accuplacer',
    shortDescription: 'College placement test for course placement decisions',
    whatItIs: 'Accuplacer is a suite of computer-adaptive tests that assess reading, writing, and math skills. Colleges use it to place students in appropriate-level courses, not for admission decisions.',
    whoShouldTake: 'Students enrolling in community colleges or some four-year institutions that require placement testing. It\'s also used by some high schools for dual enrollment programs.',
    whyItMatters: 'Your Accuplacer scores determine whether you can enroll directly in college-level courses or need to take developmental (remedial) courses first. Placing into college-level courses saves time and money.',
    whenToTake: 'Typically taken after you\'ve been admitted to a college but before you register for classes. Your college will provide testing dates and locations.',
    icon: 'analytics-outline',
    color: '#00796B',
    bgColor: '#E0F2F1',
    links: [
      { label: 'Accuplacer Info', url: 'https://accuplacer.collegeboard.org/' },
      { label: 'Free Practice App', url: 'https://accuplacer.collegeboard.org/students/prepare-for-accuplacer/practice' },
    ],
    milestones: [
      {
        id: 'accuplacer-schedule',
        label: 'Schedule test',
        taskTitle: 'Schedule Accuplacer test at college',
        offsetDays: 14,
        notes: 'Source: Test Prep - Accuplacer. Contact your college\'s testing center.',
      },
      {
        id: 'accuplacer-practice',
        label: 'Use practice app',
        taskTitle: 'Complete Accuplacer practice questions',
        offsetDays: 7,
        notes: 'Source: Test Prep - Accuplacer. The free College Board app has official practice questions.',
      },
      {
        id: 'accuplacer-review-math',
        label: 'Review math skills',
        taskTitle: 'Review algebra and arithmetic for Accuplacer',
        offsetDays: 14,
        notes: 'Source: Test Prep - Accuplacer. Math placement is often the most impactful section.',
      },
    ],
  },
  {
    id: 'state_grad',
    name: 'State Graduation Test',
    shortDescription: 'Required test for high school graduation in many states',
    whatItIs: 'Many states require students to pass standardized tests to graduate high school. These tests typically cover English/Language Arts and Mathematics, and sometimes Science and Social Studies. Requirements vary by state.',
    whoShouldTake: 'All students in states that require graduation testing. Check with your school counselor about your state\'s specific requirements and which tests you need to pass.',
    whyItMatters: 'Passing your state\'s graduation test is required to receive your high school diploma. Most states offer multiple attempts if you don\'t pass on the first try.',
    whenToTake: 'Timing varies by state, but most students take these tests in 10th or 11th grade. Your school will schedule the tests and notify you of dates.',
    icon: 'school-outline',
    color: '#C2185B',
    bgColor: '#FCE4EC',
    links: [
      { label: 'Check Your State Requirements', url: 'https://www.edweek.org/teaching-learning/which-states-require-students-to-pass-a-test-to-graduate-a-new-look' },
    ],
    milestones: [
      {
        id: 'state-ask-counselor',
        label: 'Ask counselor about requirements',
        taskTitle: 'Ask counselor about state graduation test requirements',
        offsetDays: 7,
        notes: 'Source: Test Prep - State Graduation Test. Requirements vary by state.',
      },
      {
        id: 'state-practice',
        label: 'Review practice materials',
        taskTitle: 'Review state graduation test practice materials',
        offsetDays: 14,
        notes: 'Source: Test Prep - State Graduation Test. Your school may provide practice resources.',
      },
      {
        id: 'state-check-dates',
        label: 'Check test dates',
        taskTitle: 'Confirm state graduation test dates with school',
        offsetDays: 30,
        notes: 'Source: Test Prep - State Graduation Test. Tests are usually administered during the school day.',
      },
    ],
  },
]

export function getTestById(id: string): TestPrepItem | undefined {
  return TESTS.find(test => test.id === id)
}
